import { Inter } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";

import Header from "../components/header/Header";
import Footer from "../components/footer/Footer";
import Lines from "components/Lines";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Baig Associates",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-100">
        <Providers>
          <Header />
          <Lines />
          {children}
        </Providers>
      </body>
    </html>
  );
}
